CREATE TABLE HOTELS
   (   "HOTEL_NAME"      VARCHAR2(20 BYTE) NOT NULL ENABLE,
       "REGION_NAME"     VARCHAR2(20 BYTE) NOT NULL ENABLE,
       "STAR_RATING"     NUMBER(1,0)       NOT NULL ENABLE,
       "CUSTOMER_RATING" NUMBER(2,1)       NOT NULL ENABLE,
       CONSTRAINT "HOTELS_PK" PRIMARY KEY ("HOTEL_NAME")
       USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255);

CREATE TABLE "HOTEL_AMENITIES"
   (   "HOTEL_NAME"          VARCHAR2(20 BYTE)  NOT NULL ENABLE,
       "AMENITY_NAME"        VARCHAR2(80 BYTE)  NOT NULL ENABLE,
       "AMENITY_DESCRIPTION" VARCHAR2(200 BYTE) NOT NULL ENABLE,
       "CHARGABLE_Y_OR_N"    VARCHAR2(1 BYTE)   NOT NULL ENABLE,
       CONSTRAINT "HOTEL_AMENITIES_PK" PRIMARY KEY ("HOTEL_NAME", "AMENITY_NAME") USING INDEX ENABLE,
       CONSTRAINT "HOTEL_AMENITIES_CHK1" CHECK (CHARGABLE_Y_OR_N IN ('Y','N')) ENABLE,
       CONSTRAINT "HOTEL_AMENITIES_CHK2" CHECK (AMENITY_NAME = UPPER(AMENITY_NAME)) ENABLE,
       CONSTRAINT "HOTEL_AMENITIES_FK1" FOREIGN KEY ("HOTEL_NAME")
          REFERENCES "HOTELS" ("HOTEL_NAME") ON DELETE CASCADE ENABLE
   );

CREATE INDEX "HOTEL_AMENITIES_AMENITY_NAME" ON "HOTEL_AMENITIES" ("AMENITY_NAME");

CREATE TABLE "HOTEL_ROOMS"
   (   "HOTEL_NAME"            VARCHAR2(20 BYTE)  NOT NULL ENABLE,
       "ROOM_NUMBER"           NUMBER(5,0)        NOT NULL ENABLE,
       "ROOM_SPECIAL_FEATURES" VARCHAR2(200 BYTE),
       CONSTRAINT "HOTEL_ROOMS_PK" PRIMARY KEY ("HOTEL_NAME", "ROOM_NUMBER")
       USING INDEX ENABLE);

CREATE INDEX "HOTEL_ROOMS_ROOM_IDX" ON "HOTEL_ROOMS" ("ROOM_NUMBER");

CREATE TABLE "CUSTOMERS"
   (   "CUSTOMER_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
       CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_NAME")
       USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255);

CREATE TABLE "ROOM_BOOKINGS"
   (   "BOOKING_ID"    NUMBER            NOT NULL ENABLE,
       "HOTEL_NAME"    VARCHAR2(30 BYTE) NOT NULL ENABLE,
       "CUSTOMER_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
       "ROOM_NUMBER"   NUMBER(*,0)       NOT NULL ENABLE,
       "START_DATE"    DATE              NOT NULL ENABLE,
       "END_DATE"      DATE              NOT NULL ENABLE,
       CONSTRAINT "ROOM_BOOKINGS_PK" PRIMARY KEY ("BOOKING_ID") USING INDEX ENABLE,
       CONSTRAINT "START_BEFORE_END" CHECK (START_DATE < END_DATE) ENABLE,
       CONSTRAINT "ROOM_BOOKINGS_START_IS_MIDNIGHT" CHECK (START_DATE = TRUNC(START_DATE)) ENABLE,
       CONSTRAINT "ROOM_BOOKINGS_END_IS_MIDNIGHT" CHECK (END_DATE = TRUNC(END_DATE)) ENABLE,
       CONSTRAINT "ROOM_BOOKINGS_HOTEL_ROOM" FOREIGN KEY ("HOTEL_NAME", "ROOM_NUMBER")
          REFERENCES "HOTEL_ROOMS" ("HOTEL_NAME", "ROOM_NUMBER") ON DELETE CASCADE ENABLE,
       CONSTRAINT "ROOM_BOOKINGS_FK1" FOREIGN KEY ("HOTEL_NAME")
          REFERENCES "HOTELS" ("HOTEL_NAME") ENABLE,
       CONSTRAINT "ROOM_BOOKINGS_FK2" FOREIGN KEY ("CUSTOMER_NAME")
          REFERENCES "CUSTOMERS" ("CUSTOMER_NAME") ENABLE
   );

CREATE INDEX "ROOM_BOOKINGS_CUSTOMER" ON "ROOM_BOOKINGS" ("CUSTOMER_NAME")
   PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
   TABLESPACE "USERS";

CREATE INDEX "ROOM_BOOKINGS_HOTEL_NAME" ON "ROOM_BOOKINGS" ("HOTEL_NAME")
   PCTFREE 10 INITRANS  2 MAXTRANS 255 COMPUTE STATISTICS
   TABLESPACE "USERS";

CREATE OR REPLACE VIEW HOTEL_REGIONS
   ("REGION_NAME", "MIN_STAR_RATING", "MAX_STAR_RATING"
   , "MIN_CUSTOMER_RATING", "CUSTOMER_STAR_RATING", "HOTELS_IN_REGION") AS
SELECT region_name
,      min(star_rating)     min_star_rating
,      max(star_rating)     max_star_rating
,      min(customer_rating) min_customer_rating
,      max(customer_rating) customer_star_rating
,      count(*)             hotels_in_region
FROM   hotels
group by REGION_NAME;

CREATE OR REPLACE VIEW "HOTEL_AMENITIES_SUMMARY"
   ("AMENITY_NAME", "PERCENT_TIME_CHARGABLE", "HOTELS_WITH_AMENITY") AS
SELECT AMENITY_NAME
,      (SUM(DECODE(CHARGABLE_Y_OR_N,'Y',1,0)) / count(*)) * 100 PERCENT_TIME_CHARGABLE
,      COUNT(*) hotels_with_amenity
FROM   HOTEL_AMENITIES
GROUP BY AMENITY_NAME;

CREATE SEQUENCE "BOOKING_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;

CREATE SEQUENCE complaint_id_seq;
