DROP VIEW HOTEL_REGIONS;
DROP VIEW HOTEL_AMENITIES_SUMMARY;

DROP TABLE ROOM_BOOKINGS;
DROP TABLE CUSTOMERS;
DROP TABLE HOTEL_AMENITIES;
DROP TABLE HOTEL_ROOMS;
DROP TABLE HOTELS;

DROP SEQUENCE BOOKING_ID_SEQ;
DROP SEQUENCE complaint_id_seq;
